export enum ActionType {
    CREATE_MARKER = 'CREATE_MARKER',
    DELETE_MARKER = 'DELETE_MARKER',
    EDIT_MARKER = 'EDIT_MARKER',
    SET_CURRENT_MARKER = 'SET_CURRENT_MARKER',
    CLEAR_ROUTE = 'CLEAR_ROUTE',
    CHANGE_TRAVEL_MODE = 'CHANGE_TRAVEL_MODE',
    LOAD_GOOGLE = 'LOAD_GOOGLE',
    CHANGE_CATEGORY = 'CHANGE_CATEGORY',
    GET_PLACE_DETAILS = 'GET_PLACE_DETAILS',
}
